---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: ec2-centos6
    image: ami-07fa74e425f2abf29
    instance_type: t2.micro
    vpc_subnet_id: subnet-d25fb0b8
    groups:
      - centos
  - name: ec2-centos7
    image: ami-04cf43aca3e6f3de3
    instance_type: t2.micro
    vpc_subnet_id: subnet-d25fb0b8
    groups:
      - centos
provisioner:
  name: ansible
  inventory:
    group_vars:
      centos:
        ansible_ssh_user: centos
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
